import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "naive-pattern-matching",
    title: "Naive Pattern Matching",
    titleAr: "مطابقة الأنماط الساذجة",
    category: "strings",
    difficulty: "Beginner",
    tags: ["string matching", "brute force", "O(nm)"],
    tagsAr: ["مطابقة نصوص", "القوة الغاشمة", "O(nm)"],
    summary: "Tries the pattern at every text position, comparing character by character — simple but O(nm).",
    summaryAr: "يجرّب النمط عند كل موضع في النص، مقارنًا حرفًا حرفًا — بسيط لكن بتكلفة O(nm).",
    renderer: "string",
  },
  {
    slug: "kmp",
    title: "Knuth–Morris–Pratt (KMP)",
    titleAr: "خوارزمية كنوث-موريس-برات (KMP)",
    category: "strings",
    difficulty: "Advanced",
    tags: ["string matching", "failure function", "O(n+m)", "linear"],
    tagsAr: ["مطابقة نصوص", "دالة الفشل", "O(n+m)", "خطي"],
    summary: "Precomputes a failure function so mismatches skip ahead without ever re-scanning text — O(n + m).",
    summaryAr: "يحسب مسبقًا دالة فشل بحيث يتخطى عدم التطابق إلى الأمام دون إعادة مسح النص أبدًا — O(n + m).",
    renderer: "string",
  },
  {
    slug: "rabin-karp",
    title: "Rabin-Karp String Matching",
    titleAr: "مطابقة النصوص برابين-كارب",
    category: "strings",
    difficulty: "Intermediate",
    tags: ["string matching", "rolling hash", "hashing", "average O(n+m)"],
    tagsAr: ["مطابقة نصوص", "تجزئة متدحرجة", "تجزئة", "متوسط O(n+m)"],
    summary: "Hashes each text window and only compares characters when hashes collide — average O(n + m).",
    summaryAr: "يجزّئ كل نافذة من النص ولا يقارن الحروف إلا عند تصادم التجزئات — بمتوسط O(n + m).",
    renderer: "string",
  },
  {
    slug: "z-algorithm",
    title: "Z-Algorithm",
    titleAr: "خوارزمية Z",
    category: "strings",
    difficulty: "Advanced",
    tags: ["string matching", "Z-array", "prefix matching", "linear"],
    tagsAr: ["مطابقة نصوص", "مصفوفة Z", "مطابقة البادئة", "خطي"],
    summary: "Computes for every position the longest match with the string's own prefix (Z-array) in O(n), finding all pattern occurrences.",
    summaryAr: "يحسب لكل موضع أطول تطابق مع بادئة السلسلة نفسها (مصفوفة Z) في O(n)، فيجد كل تكرارات النمط.",
    renderer: "string",
  },
  {
    slug: "boyer-moore",
    title: "Boyer-Moore (Bad Character Rule)",
    titleAr: "خوارزمية باير-مور (قاعدة الحرف السيئ)",
    category: "strings",
    difficulty: "Advanced",
    tags: ["string matching", "bad character rule", "right-to-left", "sublinear"],
    tagsAr: ["مطابقة نصوص", "قاعدة الحرف السيئ", "من اليمين إلى اليسار", "دون الخطي"],
    summary: "Compares the pattern right-to-left and uses the bad-character rule to skip large chunks of text — often sublinear in practice.",
    summaryAr: "يقارن النمط من اليمين إلى اليسار ويستخدم قاعدة الحرف السيئ لتخطي أجزاء كبيرة من النص — غالبًا دون الخطي عمليًا.",
    renderer: "string",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "naive-pattern-matching": () => import("./naive-pattern-matching"),
  kmp: () => import("./kmp"),
  "rabin-karp": () => import("./rabin-karp"),
  "z-algorithm": () => import("./z-algorithm"),
  "boyer-moore": () => import("./boyer-moore"),
};
