import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "stack-operations",
    title: "Stack (LIFO)",
    titleAr: "المكدس (LIFO)",
    category: "stacks-queues",
    difficulty: "Beginner",
    tags: ["stack", "LIFO", "O(1) operations"],
    tagsAr: ["مكدس", "LIFO", "عمليات O(1)"],
    summary: "A last-in-first-out structure supporting push, pop, and peek — each in O(1).",
    summaryAr: "هيكل يعمل بمبدأ الوارد أخيرًا يخرج أولًا يدعم الدفع (push) والإخراج (pop) والاطلاع (peek) — كل منها بزمن O(1).",
    renderer: "callstack",
  },
  {
    slug: "queue-operations",
    title: "Queue (FIFO)",
    titleAr: "الطابور (FIFO)",
    category: "stacks-queues",
    difficulty: "Beginner",
    tags: ["queue", "FIFO", "O(1) operations"],
    tagsAr: ["طابور", "FIFO", "عمليات O(1)"],
    summary: "A first-in-first-out structure supporting enqueue at the rear and dequeue from the front in O(1).",
    summaryAr: "هيكل يعمل بمبدأ الوارد أولًا يخرج أولًا يدعم الإضافة (enqueue) في المؤخرة والإزالة (dequeue) من المقدمة بزمن O(1).",
    renderer: "list",
  },
  {
    slug: "balanced-parentheses",
    title: "Balanced Parentheses",
    titleAr: "الأقواس المتوازنة",
    category: "stacks-queues",
    difficulty: "Beginner",
    tags: ["stack", "matching", "validation", "brackets"],
    tagsAr: ["مكدس", "مطابقة", "تحقّق", "أقواس"],
    summary: "Uses a stack to verify that every opening bracket has a correctly ordered matching closing bracket.",
    summaryAr: "يستخدم مكدسًا للتحقق من أن لكل قوس فتح قوس إغلاق مطابقًا مرتّبًا بشكل صحيح.",
    renderer: "callstack",
  },
  {
    slug: "min-stack",
    title: "Min-Stack (O(1) minimum)",
    titleAr: "المكدس الأصغري (أصغر قيمة بزمن O(1))",
    category: "stacks-queues",
    difficulty: "Intermediate",
    tags: ["stack", "design", "O(1)", "auxiliary"],
    tagsAr: ["مكدس", "تصميم", "O(1)", "مساعد"],
    summary: "A stack that also returns its minimum in O(1) by caching a running minimum with every pushed value.",
    summaryAr: "مكدس يعيد أيضًا أصغر قيمة فيه بزمن O(1) عبر تخزين قيمة صغرى جارية مع كل قيمة مدفوعة.",
    renderer: "callstack",
  },
  {
    slug: "circular-queue",
    title: "Circular Queue (Ring Buffer)",
    titleAr: "الطابور الحلقي (مخزن حلقي)",
    category: "stacks-queues",
    difficulty: "Intermediate",
    tags: ["queue", "ring buffer", "modulo", "fixed capacity"],
    tagsAr: ["طابور", "مخزن حلقي", "باقي القسمة", "سعة ثابتة"],
    summary: "A fixed-size queue whose front and rear indices wrap around with modulo arithmetic, reusing freed slots.",
    summaryAr: "طابور ثابت الحجم تلتفّ فيه فهارس المقدمة والمؤخرة باستخدام حساب باقي القسمة، فيعيد استخدام الخانات المحرَّرة.",
    renderer: "array",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "stack-operations": () => import("./stack-operations"),
  "queue-operations": () => import("./queue-operations"),
  "balanced-parentheses": () => import("./balanced-parentheses"),
  "min-stack": () => import("./min-stack"),
  "circular-queue": () => import("./circular-queue"),
};
