import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "euclidean-gcd",
    title: "Euclidean Algorithm (GCD)",
    titleAr: "خوارزمية إقليدس (القاسم المشترك الأكبر)",
    category: "mathematics",
    difficulty: "Beginner",
    tags: ["number theory", "recursion", "gcd", "modulo"],
    tagsAr: ["نظرية الأعداد", "العودية", "القاسم المشترك الأكبر", "باقي القسمة"],
    summary: "Finds the greatest common divisor by repeatedly replacing (a, b) with (b, a mod b) until b is 0.",
    summaryAr: "يجد القاسم المشترك الأكبر باستبدال (a, b) بـ (b, a mod b) تكرارًا حتى تصبح b صفرًا.",
    renderer: "callstack",
  },
  {
    slug: "sieve-of-eratosthenes",
    title: "Sieve of Eratosthenes",
    titleAr: "غربال إراتوستينس",
    category: "mathematics",
    difficulty: "Beginner",
    tags: ["number theory", "primes", "sieve", "O(n log log n)"],
    tagsAr: ["نظرية الأعداد", "الأعداد الأولية", "غربال", "O(n log log n)"],
    summary: "Finds all primes up to n by repeatedly crossing out the multiples of each prime.",
    summaryAr: "يجد كل الأعداد الأولية حتى n بشطب مضاعفات كل عدد أولي تكرارًا.",
    renderer: "grid",
  },
  {
    slug: "fast-power",
    title: "Fast Power (Binary Exponentiation)",
    titleAr: "الأس السريع (الأس الثنائي)",
    category: "mathematics",
    difficulty: "Intermediate",
    tags: ["number theory", "divide & conquer", "modular arithmetic", "O(log n)"],
    tagsAr: ["نظرية الأعداد", "فرّق تسُد", "الحساب القياسي", "O(log n)"],
    summary: "Computes xⁿ (optionally mod m) in O(log n) multiplications by repeatedly squaring — the engine behind modular exponentiation in cryptography.",
    summaryAr: "يحسب xⁿ (اختياريًا mod m) بعدد عمليات ضرب O(log n) عبر التربيع المتكرر — المحرّك خلف الأس القياسي في التعمية.",
    renderer: "callstack",
  },
  {
    slug: "prime-factorization",
    title: "Prime Factorization (Trial Division)",
    titleAr: "التحليل إلى عوامل أولية (القسمة التجريبية)",
    category: "mathematics",
    difficulty: "Beginner",
    tags: ["number theory", "primes", "trial division", "O(√n)"],
    tagsAr: ["نظرية الأعداد", "الأعداد الأولية", "القسمة التجريبية", "O(√n)"],
    summary: "Decomposes n into its prime factors by dividing out each candidate 2…√n; whatever remains above 1 is itself prime.",
    summaryAr: "يحلّل n إلى عوامله الأولية بقسمة كل قاسم مرشّح 2…√n؛ وما يتبقّى فوق 1 يكون أوليًا بذاته.",
    renderer: "array",
  },
  {
    slug: "extended-euclidean",
    title: "Extended Euclidean Algorithm",
    titleAr: "خوارزمية إقليدس الموسّعة",
    category: "mathematics",
    difficulty: "Advanced",
    tags: ["number theory", "Bézout identity", "modular inverse", "gcd"],
    tagsAr: ["نظرية الأعداد", "متطابقة بيزو", "المعكوس القياسي", "القاسم المشترك الأكبر"],
    summary: "Computes gcd(a, b) plus the Bézout coefficients x, y with a·x + b·y = gcd — the key to modular inverses.",
    summaryAr: "تحسب gcd(a, b) إضافة إلى معاملَي بيزو x، y بحيث a·x + b·y = gcd — مفتاح المعكوس القياسي.",
    renderer: "table",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "euclidean-gcd": () => import("./euclidean-gcd"),
  "sieve-of-eratosthenes": () => import("./sieve-of-eratosthenes"),
  "fast-power": () => import("./fast-power"),
  "prime-factorization": () => import("./prime-factorization"),
  "extended-euclidean": () => import("./extended-euclidean"),
};
