import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "binary-tree-traversals",
    title: "Binary Tree Traversals",
    titleAr: "اجتيازات الشجرة الثنائية",
    category: "trees",
    difficulty: "Beginner",
    tags: ["tree", "DFS", "BFS", "traversal"],
    tagsAr: ["شجرة", "بحث بالعمق أولًا", "بحث بالعرض أولًا", "اجتياز"],
    summary: "Visits every node in in-order, pre-order, post-order, or level-order — the four canonical traversals.",
    summaryAr: "يزور كل عقدة بالترتيب الداخلي أو السابق أو اللاحق أو حسب المستوى — الاجتيازات الأربعة الكلاسيكية.",
    renderer: "tree",
  },
  {
    slug: "binary-search-tree",
    title: "Binary Search Tree",
    titleAr: "شجرة البحث الثنائية",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["tree", "ordered", "insert/search/delete"],
    tagsAr: ["شجرة", "مرتبة", "إدراج/بحث/حذف"],
    summary: "An ordered tree where left < node < right, giving O(h) search, insertion, and deletion.",
    summaryAr: "شجرة مرتبة حيث يسار < العقدة < يمين، مما يمنح بحثًا وإدراجًا وحذفًا بتكلفة O(h).",
    renderer: "tree",
  },
  {
    slug: "level-order-traversal",
    title: "Level-Order Traversal (BFS)",
    titleAr: "الاجتياز حسب المستوى (BFS)",
    category: "trees",
    difficulty: "Beginner",
    tags: ["tree", "bfs", "queue", "traversal"],
    tagsAr: ["شجرة", "بحث بالعرض أولًا", "طابور", "اجتياز"],
    summary: "Visits a binary tree breadth-first, level by level, using a FIFO queue to process nodes in order.",
    summaryAr: "يزور شجرة ثنائية بالعرض أولًا، مستوى تلو الآخر، باستخدام طابور FIFO لمعالجة العقد بترتيبها.",
    renderer: "tree",
  },
  {
    slug: "min-heap",
    title: "Min-Heap (Binary Heap)",
    titleAr: "الكومة الصغرى (الكومة الثنائية)",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["heap", "priority queue", "complete tree", "sift"],
    tagsAr: ["كومة", "طابور أولوية", "شجرة كاملة", "إزاحة"],
    summary: "Builds a binary min-heap via sift-up insertions and removes the minimum with sift-down, all in an array.",
    summaryAr: "تبني كومة صغرى ثنائية عبر إدراجات بالإصعاد، وتحذف الحد الأدنى بالإنزال، كل ذلك في مصفوفة.",
    renderer: "tree",
  },
  {
    slug: "trie",
    title: "Trie (Prefix Tree)",
    titleAr: "الشجرة اللاحقة (شجرة البادئات)",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["trie", "prefix tree", "strings", "dictionary"],
    tagsAr: ["شجرة لاحقة", "شجرة بادئات", "سلاسل نصية", "قاموس"],
    summary: "Stores a set of strings in a prefix tree, sharing common prefixes; supports fast insert and lookup by walking edges.",
    summaryAr: "تخزّن مجموعة من السلاسل النصية في شجرة بادئات، تشترك في البادئات المشتركة؛ تدعم إدراجًا وبحثًا سريعين باجتياز الحواف.",
    renderer: "tree",
  },
  {
    slug: "avl-tree",
    title: "AVL Tree (Self-Balancing BST)",
    titleAr: "شجرة AVL (شجرة بحث ثنائية ذاتية التوازن)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "self-balancing", "rotations", "balance factor"],
    tagsAr: ["شجرة", "ذاتية التوازن", "دورانات", "عامل التوازن"],
    summary: "A height-balanced binary search tree that rotates after inserts to keep every balance factor in {−1, 0, +1}.",
    summaryAr: "شجرة بحث ثنائية متوازنة الارتفاع تُجري دورانات بعد الإدراج للحفاظ على كل عوامل التوازن ضمن {−1، 0، +1}.",
    renderer: "tree",
  },
  {
    slug: "segment-tree",
    title: "Segment Tree (Range Queries)",
    titleAr: "شجرة المجالات (استعلامات المجال)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "range query", "point update", "divide and conquer"],
    tagsAr: ["شجرة", "استعلام مجال", "تحديث نقطي", "فرّق تسد"],
    summary: "Answers range-sum queries and point updates in O(log n) by storing partial sums over a binary tree of index ranges.",
    summaryAr: "تُجيب عن استعلامات مجموع المجال والتحديثات النقطية بزمن O(log n) عبر تخزين مجاميع جزئية فوق شجرة ثنائية من مجالات الفهارس.",
    renderer: "tree",
  },
  {
    slug: "fenwick-tree",
    title: "Fenwick Tree (Binary Indexed Tree)",
    titleAr: "شجرة فينويك (الشجرة الثنائية المفهرسة)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["BIT", "prefix sum", "bit manipulation", "range query"],
    tagsAr: ["BIT", "مجموع البادئة", "معالجة البتات", "استعلام مجال"],
    summary: "A compact array that answers prefix-sum queries and point updates in O(log n) using the low-bit trick i & −i.",
    summaryAr: "مصفوفة مدمجة تُجيب عن استعلامات مجموع البادئة والتحديثات النقطية بزمن O(log n) باستخدام حيلة البت الأدنى i & −i.",
    renderer: "array",
  },
  {
    slug: "red-black-tree",
    title: "Red-Black Tree",
    titleAr: "الشجرة الحمراء-السوداء",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "self-balancing", "recoloring", "rotations"],
    tagsAr: ["شجرة", "ذاتية التوازن", "إعادة تلوين", "دورانات"],
    summary: "A self-balancing BST that uses node colors and 5 invariants to guarantee O(log n) operations with few rotations.",
    summaryAr: "شجرة بحث ثنائية ذاتية التوازن تستخدم ألوان العقد و5 ثوابت لضمان عمليات O(log n) بدورانات قليلة.",
    renderer: "tree",
  },
  {
    slug: "b-tree",
    title: "B-Tree",
    titleAr: "شجرة B",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "balanced", "multiway", "database index"],
    tagsAr: ["شجرة", "متوازنة", "متعددة الطرق", "فهرس قاعدة بيانات"],
    summary: "A balanced multiway search tree where nodes hold many keys and split when full, keeping all leaves at the same depth.",
    summaryAr: "شجرة بحث متعددة الطرق متوازنة تحمل عقدها مفاتيح كثيرة وتنقسم عند الامتلاء، مبقية كل الأوراق في نفس العمق.",
    renderer: "tree",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "binary-tree-traversals": () => import("./binary-tree-traversals"),
  "binary-search-tree": () => import("./binary-search-tree"),
  "level-order-traversal": () => import("./level-order-traversal"),
  "min-heap": () => import("./min-heap"),
  "trie": () => import("./trie"),
  "avl-tree": () => import("./avl-tree"),
  "segment-tree": () => import("./segment-tree"),
  "fenwick-tree": () => import("./fenwick-tree"),
  "red-black-tree": () => import("./red-black-tree"),
  "b-tree": () => import("./b-tree"),
};
