import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "binary-tree-traversals",
    title: "Binary Tree Traversals",
    category: "trees",
    difficulty: "Beginner",
    tags: ["tree", "DFS", "BFS", "traversal"],
    summary: "Visits every node in in-order, pre-order, post-order, or level-order — the four canonical traversals.",
    renderer: "tree",
  },
  {
    slug: "binary-search-tree",
    title: "Binary Search Tree",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["tree", "ordered", "insert/search/delete"],
    summary: "An ordered tree where left < node < right, giving O(h) search, insertion, and deletion.",
    renderer: "tree",
  },
  {
    slug: "level-order-traversal",
    title: "Level-Order Traversal (BFS)",
    category: "trees",
    difficulty: "Beginner",
    tags: ["tree", "bfs", "queue", "traversal"],
    summary: "Visits a binary tree breadth-first, level by level, using a FIFO queue to process nodes in order.",
    renderer: "tree",
  },
  {
    slug: "min-heap",
    title: "Min-Heap (Binary Heap)",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["heap", "priority queue", "complete tree", "sift"],
    summary: "Builds a binary min-heap via sift-up insertions and removes the minimum with sift-down, all in an array.",
    renderer: "tree",
  },
  {
    slug: "trie",
    title: "Trie (Prefix Tree)",
    category: "trees",
    difficulty: "Intermediate",
    tags: ["trie", "prefix tree", "strings", "dictionary"],
    summary: "Stores a set of strings in a prefix tree, sharing common prefixes; supports fast insert and lookup by walking edges.",
    renderer: "tree",
  },
  {
    slug: "avl-tree",
    title: "AVL Tree (Self-Balancing BST)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "self-balancing", "rotations", "balance factor"],
    summary: "A height-balanced binary search tree that rotates after inserts to keep every balance factor in {−1, 0, +1}.",
    renderer: "tree",
  },
  {
    slug: "segment-tree",
    title: "Segment Tree (Range Queries)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "range query", "point update", "divide and conquer"],
    summary: "Answers range-sum queries and point updates in O(log n) by storing partial sums over a binary tree of index ranges.",
    renderer: "tree",
  },
  {
    slug: "fenwick-tree",
    title: "Fenwick Tree (Binary Indexed Tree)",
    category: "trees",
    difficulty: "Advanced",
    tags: ["BIT", "prefix sum", "bit manipulation", "range query"],
    summary: "A compact array that answers prefix-sum queries and point updates in O(log n) using the low-bit trick i & −i.",
    renderer: "array",
  },
  {
    slug: "red-black-tree",
    title: "Red-Black Tree",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "self-balancing", "recoloring", "rotations"],
    summary: "A self-balancing BST that uses node colors and 5 invariants to guarantee O(log n) operations with few rotations.",
    renderer: "tree",
  },
  {
    slug: "b-tree",
    title: "B-Tree",
    category: "trees",
    difficulty: "Advanced",
    tags: ["tree", "balanced", "multiway", "database index"],
    summary: "A balanced multiway search tree where nodes hold many keys and split when full, keeping all leaves at the same depth.",
    renderer: "tree",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "binary-tree-traversals": () => import("./binary-tree-traversals"),
  "binary-search-tree": () => import("./binary-search-tree"),
  "level-order-traversal": () => import("./level-order-traversal"),
  "min-heap": () => import("./min-heap"),
  "trie": () => import("./trie"),
  "avl-tree": () => import("./avl-tree"),
  "segment-tree": () => import("./segment-tree"),
  "fenwick-tree": () => import("./fenwick-tree"),
  "red-black-tree": () => import("./red-black-tree"),
  "b-tree": () => import("./b-tree"),
};
