import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "n-queens",
    title: "N-Queens",
    titleAr: "الملكات الـ N",
    category: "backtracking",
    difficulty: "Intermediate",
    tags: ["backtracking", "constraint satisfaction", "recursion"],
    tagsAr: ["التراجع", "إرضاء القيود", "العودية"],
    summary: "Places N queens on an N×N board so none attack each other, backtracking whenever a conflict arises.",
    summaryAr: "يضع N ملكة على رقعة N×N بحيث لا يهاجم أيٌّ منها الأخرى، متراجعًا كلما نشأ تعارض.",
    renderer: "grid",
  },
  {
    slug: "rat-in-maze",
    title: "Rat in a Maze",
    titleAr: "الفأر في المتاه",
    category: "backtracking",
    difficulty: "Intermediate",
    tags: ["backtracking", "maze", "grid", "recursion"],
    tagsAr: ["التراجع", "متاه", "شبكة", "العودية"],
    summary: "Finds a path through a grid maze from the top-left to the bottom-right using recursive backtracking.",
    summaryAr: "يجد مسارًا عبر متاه شبكي من أعلى اليسار إلى أسفل اليمين باستخدام التراجع العودي.",
    renderer: "grid",
  },
  {
    slug: "permutations",
    title: "Permutations (Backtracking)",
    titleAr: "التباديل (بالتراجع)",
    category: "backtracking",
    difficulty: "Intermediate",
    tags: ["backtracking", "recursion", "permutations", "combinatorics"],
    tagsAr: ["التراجع", "العودية", "تباديل", "التوافيق"],
    summary: "Generates every ordering of a set by placing each unused element at the next position and backtracking.",
    summaryAr: "يولّد كل ترتيب لمجموعة بوضع كل عنصر غير مستخدم في الموضع التالي ثم التراجع.",
    renderer: "callstack",
  },
  {
    slug: "subset-sum",
    title: "Subset Sum (Backtracking)",
    titleAr: "مجموع المجموعة الجزئية (بالتراجع)",
    category: "backtracking",
    difficulty: "Intermediate",
    tags: ["backtracking", "recursion", "subset", "pruning"],
    tagsAr: ["التراجع", "العودية", "مجموعة جزئية", "التقليم"],
    summary: "Decides whether any subset of numbers adds up to a target, exploring include/exclude choices with pruning.",
    summaryAr: "يقرّر ما إذا كانت أي مجموعة جزئية من الأعداد تجمع إلى هدف، مستكشفًا خيارات التضمين/الاستبعاد مع التقليم.",
    renderer: "callstack",
  },
  {
    slug: "combinations",
    title: "Combinations (C(n,k) by Backtracking)",
    titleAr: "التوافيق (C(n,k) بالتراجع)",
    category: "backtracking",
    difficulty: "Intermediate",
    tags: ["backtracking", "combinatorics", "pruning", "C(n,k)"],
    tagsAr: ["التراجع", "التوافيق", "التقليم", "C(n,k)"],
    summary: "Generates every k-element subset of n items using a start-index that only moves forward, so each combination is produced exactly once.",
    summaryAr: "يولّد كل مجموعة جزئية من k عنصرًا من n عنصرًا باستخدام فهرس بداية يتحرك إلى الأمام فقط، فتُنتَج كل توفيقة مرة واحدة بالضبط.",
    renderer: "callstack",
  },
  {
    slug: "sudoku-solver",
    title: "Sudoku Solver (Backtracking)",
    titleAr: "حلّال سودوكو (بالتراجع)",
    category: "backtracking",
    difficulty: "Advanced",
    tags: ["backtracking", "constraint satisfaction", "pruning", "grid"],
    tagsAr: ["التراجع", "إرضاء القيود", "التقليم", "شبكة"],
    summary: "Fills the first empty cell with each candidate digit 1–9 that doesn't violate row/column/box rules, recursing and backtracking on dead ends.",
    summaryAr: "يملأ أول خلية فارغة بكل رقم مرشَّح من 1–9 لا يخالف قواعد الصف/العمود/الصندوق، مستدعيًا العودية ومتراجعًا عند الطرق المسدودة.",
    renderer: "grid",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "n-queens": () => import("./n-queens"),
  "rat-in-maze": () => import("./rat-in-maze"),
  "permutations": () => import("./permutations"),
  "subset-sum": () => import("./subset-sum"),
  "combinations": () => import("./combinations"),
  "sudoku-solver": () => import("./sudoku-solver"),
};
