import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "bubble-sort",
    title: "Bubble Sort",
    titleAr: "الترتيب الفقاعي",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "stable", "in-place", "quadratic"],
    tagsAr: ["ترتيب بالمقارنة", "مستقر", "في المكان", "تربيعي"],
    summary: "Repeatedly swaps adjacent out-of-order elements, bubbling the largest to the end each pass.",
    summaryAr: "يبدّل العناصر المتجاورة غير المرتبة مرارًا، فيصعد أكبر عنصر إلى النهاية في كل مرور.",
    renderer: "array",
  },
  {
    slug: "selection-sort",
    title: "Selection Sort",
    titleAr: "ترتيب الاختيار",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "in-place", "quadratic", "few swaps"],
    tagsAr: ["ترتيب بالمقارنة", "في المكان", "تربيعي", "تبديلات قليلة"],
    summary: "Repeatedly selects the smallest remaining element and moves it to the front, using at most n−1 swaps.",
    summaryAr: "يختار أصغر عنصر متبقٍ مرارًا وينقله إلى المقدمة، مستخدمًا على الأكثر n−1 عملية تبديل.",
    renderer: "array",
  },
  {
    slug: "insertion-sort",
    title: "Insertion Sort",
    titleAr: "ترتيب الإدراج",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "stable", "in-place", "adaptive"],
    tagsAr: ["ترتيب بالمقارنة", "مستقر", "في المكان", "متكيّف"],
    summary: "Builds a sorted prefix one element at a time, shifting larger elements right to open a slot for each key.",
    summaryAr: "يبني بادئة مرتبة عنصرًا تلو الآخر، مزيحًا العناصر الأكبر يمينًا ليفتح خانة لكل مفتاح.",
    renderer: "array",
  },
  {
    slug: "merge-sort",
    title: "Merge Sort",
    titleAr: "الترتيب بالدمج",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["divide & conquer", "stable", "O(n log n)", "not in-place"],
    tagsAr: ["فرّق تسد", "مستقر", "O(n log n)", "ليس في المكان"],
    summary: "Recursively splits the array in half, sorts each half, then merges them — guaranteed O(n log n).",
    summaryAr: "يُقسّم المصفوفة إلى نصفين عوديًا، يرتب كل نصف، ثم يدمجهما — بضمان O(n log n).",
    renderer: "array",
  },
  {
    slug: "quick-sort",
    title: "Quick Sort",
    titleAr: "الترتيب السريع",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["divide & conquer", "in-place", "unstable", "O(n log n) avg"],
    tagsAr: ["فرّق تسد", "في المكان", "غير مستقر", "O(n log n) في المتوسط"],
    summary: "Partitions around a pivot so smaller elements go left and larger go right, then recurses on each side.",
    summaryAr: "يُقسّم حول محور بحيث تذهب العناصر الأصغر يسارًا والأكبر يمينًا، ثم يعاود على كل جانب.",
    renderer: "array",
  },
  {
    slug: "heap-sort",
    title: "Heap Sort",
    titleAr: "ترتيب الكومة",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["heap", "in-place", "unstable", "O(n log n)"],
    tagsAr: ["كومة", "في المكان", "غير مستقر", "O(n log n)"],
    summary: "Builds a max-heap in the array, then repeatedly swaps the root maximum to the end and re-heapifies.",
    summaryAr: "يبني كومة عظمى داخل المصفوفة، ثم يبدّل جذرها الأكبر إلى النهاية مرارًا ويعيد التكويم.",
    renderer: "array",
  },
  {
    slug: "shell-sort",
    title: "Shell Sort",
    titleAr: "ترتيب شل",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["gap sequence", "in-place", "adaptive", "insertion-based"],
    tagsAr: ["متتالية فجوات", "في المكان", "متكيّف", "قائم على الإدراج"],
    summary: "Generalizes insertion sort by comparing elements a shrinking gap apart, moving them long distances early.",
    summaryAr: "يُعمّم ترتيب الإدراج بمقارنة عناصر متباعدة بفجوة متقلصة، فتتحرك مسافات طويلة مبكرًا.",
    renderer: "array",
  },
  {
    slug: "counting-sort",
    title: "Counting Sort",
    titleAr: "ترتيب العد",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["non-comparison", "stable", "linear", "integer keys"],
    tagsAr: ["ليس بالمقارنة", "مستقر", "خطي", "مفاتيح صحيحة"],
    summary: "Counts occurrences of each key and uses prefix sums to place elements directly — O(n + k), no comparisons.",
    summaryAr: "يحصي تكرار كل مفتاح ويستخدم مجاميع البادئة لوضع العناصر مباشرة — O(n + k)، دون مقارنات.",
    renderer: "array",
  },
  {
    slug: "radix-sort",
    title: "Radix Sort (LSD)",
    titleAr: "ترتيب الأساس (LSD)",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["non-comparison", "stable", "digit-by-digit", "linear-ish"],
    tagsAr: ["ليس بالمقارنة", "مستقر", "رقمًا برقم", "شبه خطي"],
    summary: "Sorts integers digit by digit from least to most significant, using a stable bucket pass for each digit.",
    summaryAr: "يرتب الأعداد الصحيحة رقمًا برقم من الأقل إلى الأكثر أهمية، مستخدمًا مرور دلاء مستقرًا لكل رقم.",
    renderer: "array",
  },
  {
    slug: "cocktail-shaker-sort",
    title: "Cocktail Shaker Sort",
    titleAr: "ترتيب الكوكتيل",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["bidirectional", "stable", "in-place", "bubble variant"],
    tagsAr: ["ثنائي الاتجاه", "مستقر", "في المكان", "مشتق من الفقاعي"],
    summary: "A bidirectional bubble sort that alternates forward and backward passes, sorting from both ends inward.",
    summaryAr: "ترتيب فقاعي ثنائي الاتجاه يتناوب بين مرورات أمامية وخلفية، مرتّبًا من الطرفين نحو الداخل.",
    renderer: "array",
  },
  {
    slug: "comb-sort",
    title: "Comb Sort",
    titleAr: "ترتيب المشط",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["gap sequence", "bubble variant", "in-place", "unstable"],
    tagsAr: ["متتالية فجوات", "مشتق من الفقاعي", "في المكان", "غير مستقر"],
    summary: "Improves bubble sort by comparing elements a shrinking gap apart, eliminating small trailing values fast.",
    summaryAr: "يحسّن الترتيب الفقاعي بمقارنة عناصر متباعدة بفجوة متقلصة، فيقضي على القيم الصغيرة المتأخرة بسرعة.",
    renderer: "array",
  },
  {
    slug: "bucket-sort",
    title: "Bucket Sort",
    titleAr: "ترتيب الدلاء",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["non-comparison", "distribution sort", "stable", "average O(n+k)"],
    tagsAr: ["ليس بالمقارنة", "ترتيب توزيعي", "مستقر", "متوسط O(n+k)"],
    summary: "Scatters values into range-based buckets, sorts each bucket internally, then concatenates — fast when input is uniformly distributed.",
    summaryAr: "يوزّع القيم إلى دلاء حسب المدى، يرتب كل دلو داخليًا، ثم يسلسلها — سريع عندما تكون المدخلات موزعة بانتظام.",
    renderer: "array",
  },
  {
    slug: "tim-sort",
    title: "Tim Sort (Simplified)",
    titleAr: "ترتيب تيم (مبسّط)",
    category: "sorting",
    difficulty: "Advanced",
    tags: ["hybrid sort", "stable", "insertion + merge", "O(n log n)", "real-world"],
    tagsAr: ["ترتيب هجين", "مستقر", "إدراج + دمج", "O(n log n)", "واقعي"],
    summary: "The hybrid behind Python's and Java's default sort: insertion-sort small runs, then merge them like merge sort — stable and fast on partially-sorted data.",
    summaryAr: "الترتيب الهجين خلف الترتيب الافتراضي في بايثون وجافا: يرتب دفعات صغيرة بالإدراج، ثم يدمجها كالترتيب بالدمج — مستقر وسريع على البيانات شبه المرتبة.",
    renderer: "array",
  },
  {
    slug: "pancake-sort",
    title: "Pancake Sort",
    titleAr: "ترتيب الفطائر",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["comparison sort", "flip-based", "O(n²)", "prefix reversal"],
    tagsAr: ["ترتيب بالمقارنة", "قائم على القلب", "O(n²)", "عكس البادئة"],
    summary: "Sorts using only 'flip the first k elements' operations — find the max, flip it to the front, then flip it to its final position.",
    summaryAr: "يرتب باستخدام عمليات 'اقلب أول k عنصر' فقط — أوجد الأكبر، اقلبه إلى المقدمة، ثم اقلبه إلى موضعه النهائي.",
    renderer: "array",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "bubble-sort": () => import("./bubble-sort"),
  "selection-sort": () => import("./selection-sort"),
  "insertion-sort": () => import("./insertion-sort"),
  "merge-sort": () => import("./merge-sort"),
  "quick-sort": () => import("./quick-sort"),
  "heap-sort": () => import("./heap-sort"),
  "shell-sort": () => import("./shell-sort"),
  "counting-sort": () => import("./counting-sort"),
  "radix-sort": () => import("./radix-sort"),
  "cocktail-shaker-sort": () => import("./cocktail-shaker-sort"),
  "comb-sort": () => import("./comb-sort"),
  "bucket-sort": () => import("./bucket-sort"),
  "tim-sort": () => import("./tim-sort"),
  "pancake-sort": () => import("./pancake-sort"),
};
