import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "bubble-sort",
    title: "Bubble Sort",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "stable", "in-place", "quadratic"],
    summary: "Repeatedly swaps adjacent out-of-order elements, bubbling the largest to the end each pass.",
    renderer: "array",
  },
  {
    slug: "selection-sort",
    title: "Selection Sort",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "in-place", "quadratic", "few swaps"],
    summary: "Repeatedly selects the smallest remaining element and moves it to the front, using at most n−1 swaps.",
    renderer: "array",
  },
  {
    slug: "insertion-sort",
    title: "Insertion Sort",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["comparison sort", "stable", "in-place", "adaptive"],
    summary: "Builds a sorted prefix one element at a time, shifting larger elements right to open a slot for each key.",
    renderer: "array",
  },
  {
    slug: "merge-sort",
    title: "Merge Sort",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["divide & conquer", "stable", "O(n log n)", "not in-place"],
    summary: "Recursively splits the array in half, sorts each half, then merges them — guaranteed O(n log n).",
    renderer: "array",
  },
  {
    slug: "quick-sort",
    title: "Quick Sort",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["divide & conquer", "in-place", "unstable", "O(n log n) avg"],
    summary: "Partitions around a pivot so smaller elements go left and larger go right, then recurses on each side.",
    renderer: "array",
  },
  {
    slug: "heap-sort",
    title: "Heap Sort",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["heap", "in-place", "unstable", "O(n log n)"],
    summary: "Builds a max-heap in the array, then repeatedly swaps the root maximum to the end and re-heapifies.",
    renderer: "array",
  },
  {
    slug: "shell-sort",
    title: "Shell Sort",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["gap sequence", "in-place", "adaptive", "insertion-based"],
    summary: "Generalizes insertion sort by comparing elements a shrinking gap apart, moving them long distances early.",
    renderer: "array",
  },
  {
    slug: "counting-sort",
    title: "Counting Sort",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["non-comparison", "stable", "linear", "integer keys"],
    summary: "Counts occurrences of each key and uses prefix sums to place elements directly — O(n + k), no comparisons.",
    renderer: "array",
  },
  {
    slug: "radix-sort",
    title: "Radix Sort (LSD)",
    category: "sorting",
    difficulty: "Intermediate",
    tags: ["non-comparison", "stable", "digit-by-digit", "linear-ish"],
    summary: "Sorts integers digit by digit from least to most significant, using a stable bucket pass for each digit.",
    renderer: "array",
  },
  {
    slug: "cocktail-shaker-sort",
    title: "Cocktail Shaker Sort",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["bidirectional", "stable", "in-place", "bubble variant"],
    summary: "A bidirectional bubble sort that alternates forward and backward passes, sorting from both ends inward.",
    renderer: "array",
  },
  {
    slug: "comb-sort",
    title: "Comb Sort",
    category: "sorting",
    difficulty: "Beginner",
    tags: ["gap sequence", "bubble variant", "in-place", "unstable"],
    summary: "Improves bubble sort by comparing elements a shrinking gap apart, eliminating small trailing values fast.",
    renderer: "array",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "bubble-sort": () => import("./bubble-sort"),
  "selection-sort": () => import("./selection-sort"),
  "insertion-sort": () => import("./insertion-sort"),
  "merge-sort": () => import("./merge-sort"),
  "quick-sort": () => import("./quick-sort"),
  "heap-sort": () => import("./heap-sort"),
  "shell-sort": () => import("./shell-sort"),
  "counting-sort": () => import("./counting-sort"),
  "radix-sort": () => import("./radix-sort"),
  "cocktail-shaker-sort": () => import("./cocktail-shaker-sort"),
  "comb-sort": () => import("./comb-sort"),
};
