import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "bfs",
    title: "Breadth-First Search (BFS)",
    category: "graphs",
    difficulty: "Beginner",
    tags: ["traversal", "queue", "shortest path (unweighted)", "level order"],
    summary: "Explores a graph level by level from a source using a queue — the basis of unweighted shortest paths.",
    renderer: "graph",
  },
  {
    slug: "dfs",
    title: "Depth-First Search (DFS)",
    category: "graphs",
    difficulty: "Beginner",
    tags: ["traversal", "stack", "recursion", "backtracking"],
    summary: "Explores each branch as deeply as possible before backtracking — the basis of many graph algorithms.",
    renderer: "graph",
  },
  {
    slug: "dijkstra",
    title: "Dijkstra's Shortest Path",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["shortest path", "greedy", "priority queue", "weighted"],
    summary: "Finds shortest paths from a source in a non-negative weighted graph by always settling the closest frontier node.",
    renderer: "graph",
  },
  {
    slug: "prim",
    title: "Prim's MST",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["minimum spanning tree", "greedy", "priority queue", "weighted"],
    summary: "Grows a minimum spanning tree from a start node by repeatedly adding the cheapest edge to a new vertex.",
    renderer: "graph",
  },
  {
    slug: "kruskal",
    title: "Kruskal's MST",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["minimum spanning tree", "greedy", "union-find", "weighted"],
    summary: "Sorts all edges by weight and adds each one that doesn't create a cycle, using union-find to detect cycles.",
    renderer: "graph",
  },
  {
    slug: "topological-sort",
    title: "Topological Sort (Kahn's)",
    category: "graphs",
    difficulty: "Intermediate",
    tags: ["DAG", "ordering", "in-degree", "dependencies"],
    summary: "Orders the vertices of a DAG so every edge points forward, by repeatedly removing in-degree-zero nodes.",
    renderer: "graph",
  },
  {
    slug: "bellman-ford",
    title: "Bellman-Ford Shortest Path",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "shortest path", "negative weights", "dynamic programming"],
    summary: "Finds shortest paths from a source even with negative edges by relaxing all edges V−1 times, and detects negative cycles.",
    renderer: "graph",
  },
  {
    slug: "floyd-warshall",
    title: "Floyd-Warshall (All-Pairs)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "all-pairs shortest path", "dynamic programming", "matrix"],
    summary: "Computes shortest paths between every pair of vertices by progressively allowing more intermediate vertices.",
    renderer: "table",
  },
  {
    slug: "union-find",
    title: "Union-Find (Disjoint Set Union)",
    category: "graphs",
    difficulty: "Intermediate",
    tags: ["disjoint set", "union by rank", "path compression", "connectivity"],
    summary: "Maintains a partition of elements into disjoint sets with near-constant-time union and find via rank and path compression.",
    renderer: "graph",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  bfs: () => import("./bfs"),
  dfs: () => import("./dfs"),
  dijkstra: () => import("./dijkstra"),
  prim: () => import("./prim"),
  kruskal: () => import("./kruskal"),
  "topological-sort": () => import("./topological-sort"),
  "bellman-ford": () => import("./bellman-ford"),
  "floyd-warshall": () => import("./floyd-warshall"),
  "union-find": () => import("./union-find"),
};
