import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "bfs",
    title: "Breadth-First Search (BFS)",
    titleAr: "البحث بالعرض أولًا (BFS)",
    category: "graphs",
    difficulty: "Beginner",
    tags: ["traversal", "queue", "shortest path (unweighted)", "level order"],
    tagsAr: ["اجتياز", "طابور", "أقصر مسار (غير موزون)", "ترتيب حسب المستوى"],
    summary: "Explores a graph level by level from a source using a queue — the basis of unweighted shortest paths.",
    summaryAr: "يستكشف رسمًا بيانيًا مستوى تلو الآخر انطلاقًا من عقدة مصدر باستخدام طابور — وهو أساس أقصر المسارات غير الموزونة.",
    renderer: "graph",
  },
  {
    slug: "dfs",
    title: "Depth-First Search (DFS)",
    titleAr: "البحث بالعمق أولًا (DFS)",
    category: "graphs",
    difficulty: "Beginner",
    tags: ["traversal", "stack", "recursion", "backtracking"],
    tagsAr: ["اجتياز", "مكدس", "العودية", "التراجع"],
    summary: "Explores each branch as deeply as possible before backtracking — the basis of many graph algorithms.",
    summaryAr: "يستكشف كل فرع بأقصى عمق ممكن قبل التراجع — أساس كثير من خوارزميات الرسوم البيانية.",
    renderer: "graph",
  },
  {
    slug: "dijkstra",
    title: "Dijkstra's Shortest Path",
    titleAr: "خوارزمية دايكسترا لأقصر مسار (Dijkstra)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["shortest path", "greedy", "priority queue", "weighted"],
    tagsAr: ["أقصر مسار", "جشِع", "طابور أولوية", "موزون"],
    summary: "Finds shortest paths from a source in a non-negative weighted graph by always settling the closest frontier node.",
    summaryAr: "يجد أقصر المسارات من مصدر في رسم بياني موزون بأوزان غير سالبة، بالاستقرار دومًا عند أقرب عقدة في الجبهة.",
    renderer: "graph",
  },
  {
    slug: "prim",
    title: "Prim's MST",
    titleAr: "شجرة برايم الممتدة الصغرى (Prim)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["minimum spanning tree", "greedy", "priority queue", "weighted"],
    tagsAr: ["شجرة ممتدة صغرى", "جشِع", "طابور أولوية", "موزون"],
    summary: "Grows a minimum spanning tree from a start node by repeatedly adding the cheapest edge to a new vertex.",
    summaryAr: "ينمّي شجرة ممتدة صغرى من عقدة بداية بإضافة أرخص حافة إلى رأس جديد مرارًا.",
    renderer: "graph",
  },
  {
    slug: "kruskal",
    title: "Kruskal's MST",
    titleAr: "شجرة كروسكال الممتدة الصغرى (Kruskal)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["minimum spanning tree", "greedy", "union-find", "weighted"],
    tagsAr: ["شجرة ممتدة صغرى", "جشِع", "اتحاد-بحث", "موزون"],
    summary: "Sorts all edges by weight and adds each one that doesn't create a cycle, using union-find to detect cycles.",
    summaryAr: "يرتّب كل الحواف حسب الوزن ويضيف كل حافة لا تُنشئ دورة، مستخدمًا هيكل اتحاد-بحث لاكتشاف الدورات.",
    renderer: "graph",
  },
  {
    slug: "topological-sort",
    title: "Topological Sort (Kahn's)",
    titleAr: "الترتيب الطوبولوجي (خوارزمية كاهن)",
    category: "graphs",
    difficulty: "Intermediate",
    tags: ["DAG", "ordering", "in-degree", "dependencies"],
    tagsAr: ["رسم بياني موجه غير دوري", "ترتيب", "درجة الدخول", "تبعيات"],
    summary: "Orders the vertices of a DAG so every edge points forward, by repeatedly removing in-degree-zero nodes.",
    summaryAr: "يرتّب رؤوس رسم بياني موجه غير دوري بحيث تشير كل حافة إلى الأمام، بإزالة العقد ذات درجة الدخول صفر مرارًا.",
    renderer: "graph",
  },
  {
    slug: "bellman-ford",
    title: "Bellman-Ford Shortest Path",
    titleAr: "خوارزمية بيلمان-فورد لأقصر مسار (Bellman-Ford)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "shortest path", "negative weights", "dynamic programming"],
    tagsAr: ["رسم بياني", "أقصر مسار", "أوزان سالبة", "البرمجة الديناميكية"],
    summary: "Finds shortest paths from a source even with negative edges by relaxing all edges V−1 times, and detects negative cycles.",
    summaryAr: "يجد أقصر المسارات من مصدر حتى مع وجود حواف سالبة بتخفيف كل الحواف V−1 مرة، ويكتشف الدورات السالبة.",
    renderer: "graph",
  },
  {
    slug: "floyd-warshall",
    title: "Floyd-Warshall (All-Pairs)",
    titleAr: "خوارزمية فلويد-واريشال (كل الأزواج)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "all-pairs shortest path", "dynamic programming", "matrix"],
    tagsAr: ["رسم بياني", "أقصر مسار بين كل الأزواج", "البرمجة الديناميكية", "مصفوفة"],
    summary: "Computes shortest paths between every pair of vertices by progressively allowing more intermediate vertices.",
    summaryAr: "يحسب أقصر المسارات بين كل زوج من الرؤوس، بالسماح تدريجيًا بمزيد من الرؤوس الوسيطة.",
    renderer: "table",
  },
  {
    slug: "union-find",
    title: "Union-Find (Disjoint Set Union)",
    titleAr: "اتحاد-بحث (اتحاد المجموعات المنفصلة)",
    category: "graphs",
    difficulty: "Intermediate",
    tags: ["disjoint set", "union by rank", "path compression", "connectivity"],
    tagsAr: ["مجموعة منفصلة", "الاتحاد حسب الرتبة", "ضغط المسار", "الاتصال"],
    summary: "Maintains a partition of elements into disjoint sets with near-constant-time union and find via rank and path compression.",
    summaryAr: "يحافظ على تجزئة العناصر إلى مجموعات منفصلة بعمليتي اتحاد وبحث بزمن شبه ثابت عبر الرتبة وضغط المسار.",
    renderer: "graph",
  },
  {
    slug: "tarjan-scc",
    title: "Tarjan's Strongly Connected Components",
    titleAr: "مكوّنات تارجان المتصلة بقوة (Tarjan)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "SCC", "DFS", "lowlink"],
    tagsAr: ["رسم بياني", "مكوّن متصل بقوة", "بحث بالعمق أولًا", "lowlink"],
    summary: "Finds all strongly connected components of a directed graph in a single DFS using discovery indices and lowlink values.",
    summaryAr: "يجد كل المكوّنات المتصلة بقوة في رسم بياني موجه ضمن اجتياز DFS واحد باستخدام فهارس الاكتشاف وقيم lowlink.",
    renderer: "graph",
  },
  {
    slug: "kosaraju-scc",
    title: "Kosaraju's Strongly Connected Components",
    titleAr: "مكوّنات كوساراجو المتصلة بقوة (Kosaraju)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "SCC", "DFS", "transpose"],
    tagsAr: ["رسم بياني", "مكوّن متصل بقوة", "بحث بالعمق أولًا", "النقل"],
    summary: "Finds strongly connected components with two DFS passes: order by finish time, then DFS the transposed graph.",
    summaryAr: "يجد المكوّنات المتصلة بقوة باجتيازي DFS: ترتيب حسب وقت الانتهاء، ثم DFS على الرسم البياني المنقول.",
    renderer: "graph",
  },
  {
    slug: "a-star",
    title: "A* Pathfinding",
    titleAr: "إيجاد المسار بخوارزمية A*",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "shortest path", "heuristic", "informed search"],
    tagsAr: ["رسم بياني", "أقصر مسار", "دالة استدلالية", "بحث مُوجَّه"],
    summary: "Finds the shortest path on a grid by expanding the cell that minimizes f = g + h, guided by an admissible heuristic.",
    summaryAr: "يجد أقصر مسار على شبكة بتوسيع الخلية التي تُصغِّر f = g + h، موجَّهًا بدالة استدلالية مقبولة.",
    renderer: "grid",
  },
  {
    slug: "max-flow",
    title: "Maximum Flow (Edmonds-Karp)",
    titleAr: "التدفق الأقصى (خوارزمية إدموندز-كارب)",
    category: "graphs",
    difficulty: "Advanced",
    tags: ["graph", "max-flow", "residual graph", "BFS augmenting paths"],
    tagsAr: ["رسم بياني", "التدفق الأقصى", "رسم بياني متبقٍّ", "مسارات توسيع BFS"],
    summary: "Computes the maximum flow from source to sink by repeatedly pushing flow along shortest augmenting paths found with BFS.",
    summaryAr: "يحسب التدفق الأقصى من المصدر إلى المصرف بدفع تدفق مرارًا عبر أقصر مسارات توسيع يجدها BFS.",
    renderer: "graph",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  bfs: () => import("./bfs"),
  dfs: () => import("./dfs"),
  dijkstra: () => import("./dijkstra"),
  prim: () => import("./prim"),
  kruskal: () => import("./kruskal"),
  "topological-sort": () => import("./topological-sort"),
  "bellman-ford": () => import("./bellman-ford"),
  "floyd-warshall": () => import("./floyd-warshall"),
  "union-find": () => import("./union-find"),
  "tarjan-scc": () => import("./tarjan-scc"),
  "kosaraju-scc": () => import("./kosaraju-scc"),
  "a-star": () => import("./a-star"),
  "max-flow": () => import("./max-flow"),
};
