import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "fibonacci-dp",
    title: "Fibonacci — Memoization",
    titleAr: "فيبوناتشي — التخزين المؤقت للنتائج",
    category: "dynamic-programming",
    difficulty: "Beginner",
    tags: ["dynamic programming", "memoization", "top-down", "overlapping subproblems"],
    tagsAr: ["البرمجة الديناميكية", "التخزين المؤقت للنتائج", "من الأعلى للأسفل", "مسائل فرعية متداخلة"],
    summary: "Computes Fibonacci with top-down memoization, caching each subproblem so it's solved only once.",
    summaryAr: "يحسب متتالية فيبوناتشي بالتخزين المؤقت من الأعلى للأسفل، خازنًا كل مسألة فرعية بحيث تُحل مرة واحدة فقط.",
    renderer: "callstack",
  },
  {
    slug: "knapsack-01",
    title: "0/1 Knapsack",
    titleAr: "حقيبة 0/1",
    category: "dynamic-programming",
    difficulty: "Intermediate",
    tags: ["dynamic programming", "tabulation", "optimization", "NP-hard (pseudo-poly)"],
    tagsAr: ["البرمجة الديناميكية", "الجدولة", "تحسين", "NP-صعبة (شبه كثيرة الحدود)"],
    summary: "Maximizes value under a weight limit where each item is taken whole or not at all, via a DP table.",
    summaryAr: "يعظّم القيمة ضمن حد وزني حيث يُؤخذ كل عنصر كاملًا أو يُترك، عبر جدول برمجة ديناميكية.",
    renderer: "table",
  },
  {
    slug: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    titleAr: "أطول تتابع فرعي مشترك",
    category: "dynamic-programming",
    difficulty: "Intermediate",
    tags: ["dynamic programming", "strings", "tabulation", "subsequence"],
    tagsAr: ["البرمجة الديناميكية", "سلاسل نصية", "الجدولة", "تتابع فرعي"],
    summary: "Finds the longest subsequence common to two strings by filling a 2-D DP table, then tracing it back.",
    summaryAr: "يجد أطول تتابع فرعي مشترك بين سلسلتين نصيتين بملء جدول برمجة ديناميكية ثنائي الأبعاد، ثم التتبع الرجعي.",
    renderer: "table",
  },
  {
    slug: "edit-distance",
    title: "Edit Distance (Levenshtein)",
    titleAr: "مسافة التحرير (ليفنشتاين)",
    category: "dynamic-programming",
    difficulty: "Intermediate",
    tags: ["dynamic programming", "strings", "levenshtein", "tabulation"],
    tagsAr: ["البرمجة الديناميكية", "سلاسل نصية", "ليفنشتاين", "الجدولة"],
    summary: "Computes the minimum number of insertions, deletions, and substitutions to transform one string into another.",
    summaryAr: "يحسب أقل عدد من عمليات الإدراج والحذف والاستبدال لتحويل سلسلة نصية إلى أخرى.",
    renderer: "table",
  },
  {
    slug: "coin-change",
    title: "Coin Change (Minimum Coins)",
    titleAr: "فكة العملات (أقل عدد من العملات)",
    category: "dynamic-programming",
    difficulty: "Intermediate",
    tags: ["dynamic programming", "unbounded knapsack", "optimization", "tabulation"],
    tagsAr: ["البرمجة الديناميكية", "حقيبة غير محدودة", "تحسين", "الجدولة"],
    summary: "Finds the fewest coins that sum to a target amount, allowing each denomination to be reused any number of times.",
    summaryAr: "يجد أقل عدد من العملات التي يبلغ مجموعها مبلغًا مستهدفًا، مع السماح بإعادة استخدام كل فئة أي عدد من المرات.",
    renderer: "table",
  },
  {
    slug: "maximum-subarray",
    title: "Maximum Subarray (Kadane's)",
    titleAr: "أعظم مصفوفة جزئية (خوارزمية كادين)",
    category: "dynamic-programming",
    difficulty: "Beginner",
    tags: ["dynamic programming", "kadane", "array", "greedy dp"],
    tagsAr: ["البرمجة الديناميكية", "كادين", "مصفوفة", "برمجة ديناميكية جشعة"],
    summary: "Finds the contiguous subarray with the largest sum in a single linear pass using Kadane's algorithm.",
    summaryAr: "يجد المصفوفة الجزئية المتجاورة ذات المجموع الأكبر في مرور خطي واحد باستخدام خوارزمية كادين.",
    renderer: "array",
  },
  {
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    titleAr: "أطول تتابع فرعي متزايد",
    category: "dynamic-programming",
    difficulty: "Intermediate",
    tags: ["dynamic programming", "subsequence", "array", "LIS"],
    tagsAr: ["البرمجة الديناميكية", "تتابع فرعي", "مصفوفة", "LIS"],
    summary: "Finds the longest strictly increasing subsequence via an O(n²) DP, tracking predecessors to rebuild the chain.",
    summaryAr: "يجد أطول تتابع فرعي متزايد تمامًا عبر برمجة ديناميكية بزمن O(n²)، متتبعًا الأسلاف لإعادة بناء السلسلة.",
    renderer: "array",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "fibonacci-dp": () => import("./fibonacci-dp"),
  "knapsack-01": () => import("./knapsack-01"),
  "longest-common-subsequence": () => import("./longest-common-subsequence"),
  "edit-distance": () => import("./edit-distance"),
  "coin-change": () => import("./coin-change"),
  "maximum-subarray": () => import("./maximum-subarray"),
  "longest-increasing-subsequence": () => import("./longest-increasing-subsequence"),
};
