import type { AlgorithmMeta } from "@/lib/engine/types";
import type { ModuleLoader } from "..";

export const metas: AlgorithmMeta[] = [
  {
    slug: "linear-search",
    title: "Linear Search",
    titleAr: "البحث الخطي",
    category: "searching",
    difficulty: "Beginner",
    tags: ["sequential", "unsorted ok", "O(n)"],
    tagsAr: ["تسلسلي", "يعمل مع غير المرتب", "O(n)"],
    summary: "Scans elements one by one until the target is found or the array ends — works on any array.",
    summaryAr: "يمسح العناصر واحدًا تلو الآخر حتى يُعثَر على الهدف أو تنتهي المصفوفة — يعمل مع أي مصفوفة.",
    renderer: "array",
  },
  {
    slug: "binary-search",
    title: "Binary Search",
    titleAr: "البحث الثنائي",
    category: "searching",
    difficulty: "Beginner",
    tags: ["divide & conquer", "sorted required", "O(log n)"],
    tagsAr: ["فرّق تسد", "يتطلب الترتيب", "O(log n)"],
    summary: "Repeatedly halves a sorted array, comparing the middle element to the target — O(log n) lookups.",
    summaryAr: "يُنصّف مصفوفة مرتبة مرارًا، مقارنًا العنصر الأوسط بالهدف — عمليات بحث بتكلفة O(log n).",
    renderer: "array",
  },
  {
    slug: "jump-search",
    title: "Jump Search",
    titleAr: "البحث بالقفز",
    category: "searching",
    difficulty: "Beginner",
    tags: ["sorted required", "block search", "O(√n)"],
    tagsAr: ["يتطلب الترتيب", "بحث بالكتل", "O(√n)"],
    summary: "Jumps ahead in fixed √n blocks on a sorted array, then scans the block that must contain the target.",
    summaryAr: "يقفز إلى الأمام بكتل ثابتة بحجم √n في مصفوفة مرتبة، ثم يمسح الكتلة التي لا بد أن تحتوي على الهدف.",
    renderer: "array",
  },
  {
    slug: "interpolation-search",
    title: "Interpolation Search",
    titleAr: "البحث بالاستقراء",
    category: "searching",
    difficulty: "Intermediate",
    tags: ["sorted required", "uniform data", "O(log log n) avg"],
    tagsAr: ["يتطلب الترتيب", "بيانات منتظمة", "O(log log n) متوسطًا"],
    summary: "Predicts the target's index by linear interpolation on value — near O(log log n) on uniformly distributed data.",
    summaryAr: "يتنبأ بفهرس الهدف عبر الاستقراء الخطي على القيمة — قريب من O(log log n) على البيانات الموزعة بانتظام.",
    renderer: "array",
  },
  {
    slug: "exponential-search",
    title: "Exponential Search",
    titleAr: "البحث الأسي",
    category: "searching",
    difficulty: "Intermediate",
    tags: ["sorted required", "unbounded", "O(log n)"],
    tagsAr: ["يتطلب الترتيب", "غير محدود", "O(log n)"],
    summary: "Doubles a range bound until it passes the target, then binary-searches that range — great for unbounded lists.",
    summaryAr: "يضاعف حد المجال حتى يتجاوز الهدف، ثم يُجري بحثًا ثنائيًا في ذلك المجال — ممتاز للقوائم غير المحدودة.",
    renderer: "array",
  },
  {
    slug: "ternary-search",
    title: "Ternary Search",
    titleAr: "البحث الثلاثي",
    category: "searching",
    difficulty: "Intermediate",
    tags: ["sorted required", "divide by 3", "O(log₃ n)"],
    tagsAr: ["يتطلب الترتيب", "القسمة على 3", "O(log₃ n)"],
    summary: "Divides a sorted range into three parts with two midpoints, discarding two-thirds each step.",
    summaryAr: "يقسم مجالًا مرتبًا إلى ثلاثة أجزاء بنقطتي منتصف، متخلصًا من ثلثين في كل خطوة.",
    renderer: "array",
  },
];

export const loaders: Record<string, ModuleLoader> = {
  "linear-search": () => import("./linear-search"),
  "binary-search": () => import("./binary-search"),
  "jump-search": () => import("./jump-search"),
  "interpolation-search": () => import("./interpolation-search"),
  "exponential-search": () => import("./exponential-search"),
  "ternary-search": () => import("./ternary-search"),
};
